version: '3.9'

services:
  mysql:
    image: arm64v8/mysql:oracle
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD={MYSQL_PASSWORD}
      - MYSQL_USER={MYSQL_USER}
      - MYSQL_DATABASE={MYSQL_DATABASE}
